[package]
name = "thrillview"
authors = ["Novarleeir"]
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.33.2"
eframe = "0.33.2"
egui_logger = "0.9.0"
#egui_extras = { version = "0.32.0", features = ["image", "all_loaders"] }
egui-file-dialog = { version = "0.12.0", features = ["information_view"] }
catppuccin-egui = { version = "5.7.0", default-features = false, features = ["egui33"] }
log = "0.4.27"
rust-ini = "0.21.3"
#walkdir = "2.5.0"
egui-modal = "0.8.0"
#egui_memory_editor = "0.2.12"
#egui-gizmo = "0.16.2"
#egui_ltreeview = "0.6.0"

[patch.crates-io]
egui-modal = { git = "https://github.com/n00kii/egui-modal.git", rev = "eee74f5eb003b3412f89a8e3412b4898a613c44d" }